#!/bin/sh

set -o vi

alias g="git"
alias c="clear"
alias v=vagrant
alias ack='nocorrect ack '
alias sshfs='nocorrect sshfs '
alias composer='nocorrect composer '
alias gap="git add -p"
alias t="trt "
alias mou="open /Applications/Mou.app"
alias gd="git diff"
alias gts="git for-each-ref --format='%(refname:short) <- %(upstream:short)' refs/heads"

bindkey -v
bindkey '\e[3~' delete-char
bindkey '^R' history-incremental-search-backward

export EDITOR=vim
export GIT_EDITOR=vim
export SVN_EDITOR=vim

setopt INTERACTIVE_COMMENTS

PATH=$HOME/bin:$PATH

