#!/bin/sh

# enable vim mode
set -o vi

# oh-my-zsh location
ZSH=$HOME/.oh-my-zsh

# setup oh-my-zsh
if [ ! -e $ZSH ]; then
    echo "'OH MY ZUSH!' not found, installing..."
    git clone git://github.com/robbyrussell/oh-my-zsh.git $ZSH
fi

# oh-my-zsh theme
ZSH_THEME="robbyrussell"

# oh-my-zsh plugins
plugins=(git osx extract)

# load oh-my-zsh
source $ZSH/oh-my-zsh.sh

# scm_breeze location
SCMB="$HOME/.scm_breeze"

# setup scm_breeze
if [ ! -e $SCMB ]; then
    echo "'SCM Breeze' not found, installing..."
    git clone git://github.com/ndbroadbent/scm_breeze.git $SCMB
    source "$SCMB/lib/scm_breeze.sh"
    scmbDir=$SCMB
    _create_or_patch_scmbrc
fi

# load scm_breeze
source "$SCMB/scm_breeze.sh"

# shortcuts and aliases
alias g="git"
alias c="clear"
alias v=vagrant
alias ack='nocorrect ack '
alias sshfs='nocorrect sshfs '
alias composer='nocorrect composer '
alias gap="git add -p"
alias t="trt "
alias mou="open /Applications/Mou.app"
alias gd="git diff"
alias gts="git for-each-ref --format='%(refname:short) <- %(upstream:short)' refs/heads"

bindkey -v
bindkey '\e[3~' delete-char
bindkey '^R' history-incremental-search-backward

# vim as default editor
export EDITOR=vim
export GIT_EDITOR=$EDITOR
export SVN_EDITOR=$EDITOR

# allow hash as comment
setopt INTERACTIVE_COMMENTS

# local bin folder
PATH=$HOME/bin:$PATH

